# Generated by Django 4.2.3 on 2024-12-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('surname', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('personal_email', models.EmailField(max_length=100)),
                ('work_email', models.EmailField(max_length=100)),
                ('work_email_password', models.CharField(max_length=100)),
                ('DNI_file', models.FileField(upload_to='human_resources/')),
                ('teacher_authorization', models.FileField(upload_to='human_resources/')),
                ('declaration_data_protection', models.FileField(upload_to='human_resources/')),
                ('declaration_no_sexual_offenses', models.FileField(upload_to='human_resources/')),
                ('declaration_not_serving_sentence', models.FileField(upload_to='human_resources/')),
                ('driving_license', models.CharField(max_length=100)),
            ],
        ),
    ]
