# Generated by Django 4.2.3 on 2024-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_employee_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='control_l_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='control_l_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
