# Generated by Django 4.2.3 on 2024-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_teacher_control_l_password_teacher_control_l_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='driving_license',
            field=models.FileField(upload_to='human_resources/'),
        ),
    ]
