# Generated by Django 4.2.3 on 2024-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_employeesoftware_remove_teacher_control_l_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='observations',
            field=models.TextField(default='', verbose_name='observaciones'),
            preserve_default=False,
        ),
    ]
