# Generated by Django 4.2.3 on 2024-12-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_employee_observations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeAccounts',
            new_name='EmployeeSoftwareAccount',
        ),
    ]
