# Generated by Django 4.2.3 on 2024-12-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_rename_employeeaccounts_employeesoftwareaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DNI_file',
            field=models.FileField(upload_to='docs/human_resources/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='declaration_data_protection',
            field=models.FileField(upload_to='docs/human_resources/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='declaration_no_sexual_offenses',
            field=models.FileField(upload_to='docs/human_resources/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='declaration_not_serving_sentence',
            field=models.FileField(upload_to='docs/human_resources/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='driving_license',
            field=models.FileField(upload_to='docs/human_resources/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_authorization',
            field=models.FileField(upload_to='docs/human_resources/'),
        ),
    ]
