# Generated by Django 4.2.3 on 2024-12-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_alter_employee_dni_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_email_password',
        ),
    ]
