# Generated by Django 4.2.3 on 2025-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0011_remove_employee_work_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_administrative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
