# Generated by Django 4.2.3 on 2025-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0012_employee_is_administrative_employee_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_degree',
            field=models.FileField(default='', upload_to='docs/human_resources/'),
            preserve_default=False,
        ),
    ]
