# Generated by Django 4.2.3 on 2025-01-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0013_teacher_teacher_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('file', models.FileField(upload_to='docs/human_resources/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee')),
            ],
        ),
    ]
