# Generated by Django 4.2.3 on 2025-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0015_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hours_a_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_temporal',
            field=models.BooleanField(default=False),
        ),
    ]
