# Generated by Django 4.2.3 on 2025-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0016_contract_hours_a_week_contract_is_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='name',
        ),
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
