# Generated by Django 4.2.3 on 2025-01-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0018_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='file',
            field=models.FileField(default='', upload_to='docs/human_resources/'),
            preserve_default=False,
        ),
    ]
