# Generated by Django 4.2.3 on 2025-01-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0021_vacations_absences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absences',
            new_name='Absence',
        ),
        migrations.RenameModel(
            old_name='Vacations',
            new_name='Vacation',
        ),
    ]
