# Generated by Django 4.2.3 on 2025-01-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0022_rename_absences_absence_rename_vacations_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='absence',
            name='reason',
            field=models.TextField(default='', verbose_name='Reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absence',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='absence',
            name='init_date',
            field=models.DateField(),
        ),
    ]
