# Generated by Django 4.2.3 on 2025-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0023_absence_hours_absence_reason_alter_absence_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='is_justified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absence',
            name='is_sick_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absence',
            name='justification',
            field=models.FileField(default='', upload_to='docs/human_resources/'),
            preserve_default=False,
        ),
    ]
