# Generated by Django 4.2.3 on 2025-01-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_tax_remove_product_taxe_rate_product_tax'),
        ('human_resources', '0024_absence_is_justified_absence_is_sick_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrative',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.section'),
            preserve_default=False,
        ),
    ]
