# Generated by Django 4.2.3 on 2024-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingschoolsection',
            name='zone',
            field=models.TextField(blank=True),
        ),
    ]
