# Generated by Django 4.2.3 on 2023-07-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingPermission',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
