# Generated by Django 4.2.3 on 2024-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='mobile_phone',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
