# Generated by Django 4.2.3 on 2024-12-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_drivinglicense_product_drivingpractices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrivingPractices',
            new_name='DrivingPractice',
        ),
    ]
