# Generated by Django 4.2.3 on 2024-12-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_rename_drivingpractices_drivingpractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='igic_included',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
