# Generated by Django 4.2.3 on 2024-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_product_igic_included'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='igic_included',
            new_name='taxes_included',
        ),
        migrations.AddField(
            model_name='product',
            name='taxe_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
