# Generated by Django 4.2.3 on 2024-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_igic_included_product_taxes_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxe_rate',
            field=models.FloatField(default=7.0),
        ),
    ]
