# Generated by Django 4.2.3 on 2025-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_tax_remove_product_taxe_rate_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.AddField(
            model_name='section',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='postal_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='province',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DrivingPractice',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
