# Generated by Django 4.2.3 on 2025-02-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_product_tax_section_city_section_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
