# Generated by Django 4.2.3 on 2025-01-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0008_tax_remove_product_taxe_rate_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('expedition_date', models.DateField()),
                ('has_glasses', models.BooleanField()),
                ('has_limited_validation', models.BooleanField()),
                ('has_restricted_conditions', models.BooleanField()),
                ('medical_certificate_file', models.FileField(upload_to='students/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('dni', models.CharField(max_length=100)),
                ('dni_expire_date', models.DateField()),
                ('profile_picture', models.ImageField(upload_to='docs/profile_pictures')),
                ('address', models.CharField(max_length=100)),
                ('dni_file', models.FileField(upload_to='students/')),
                ('acquisition_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.acquisitionmethods')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.language')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_protection_file', models.FileField(upload_to='docs/data_protection')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.drivinglicense')),
                ('medical_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.medicalcertificate')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registrationstate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.student')),
            ],
        ),
    ]
