# Generated by Django 4.2.3 on 2025-01-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcquisitionMethods',
            new_name='LeadSource',
        ),
    ]
