# Generated by Django 4.2.3 on 2025-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0002_rename_acquisitionmethods_leadsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'verbose_name': 'Como nos conociste', 'verbose_name_plural': 'Como nos conociste'},
        ),
        migrations.AlterModelOptions(
            name='medicalcertificate',
            options={'verbose_name': 'Certificado médico', 'verbose_name_plural': 'Certificados médicos'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Matricula', 'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterModelOptions(
            name='registrationcontract',
            options={'verbose_name': 'Contrato de mátriculación', 'verbose_name_plural': 'Contratos de matriculación'},
        ),
        migrations.AlterModelOptions(
            name='registrationstate',
            options={'verbose_name': 'Estado de la matrícula', 'verbose_name_plural': 'Estados de la matrícula'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='registrationstate',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
