# Generated by Django 4.2.3 on 2025-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0003_alter_language_options_alter_leadsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationstate',
            name='is_pasive_status',
            field=models.BooleanField(default=False),
        ),
    ]
