# Generated by Django 4.2.3 on 2025-01-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0004_registrationstate_is_pasive_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationstate',
            old_name='is_pasive_status',
            new_name='is_pasive',
        ),
    ]
