# Generated by Django 4.2.3 on 2025-01-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0005_rename_is_pasive_status_registrationstate_is_pasive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasnferOfRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_theorical_exam_pass', models.BooleanField()),
                ('times_presented_to_theorical_exam', models.IntegerField()),
                ('date_of_last_presented_to_theorical_exam', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registrationcontract'),
        ),
    ]
