# Generated by Django 4.2.3 on 2025-01-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0006_trasnferofregistration_registration_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TheoricalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='transfer',
            new_name='traslado',
        ),
    ]
