# Generated by Django 4.2.3 on 2025-01-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0007_practicalexam_theoricalexam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='medical_certificate',
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='administrative_management.registration'),
            preserve_default=False,
        ),
    ]
