# Generated by Django 4.2.3 on 2025-01-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0008_remove_registration_medical_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='traslado',
        ),
        migrations.AddField(
            model_name='registration',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registrationcontract'),
        ),
    ]
