# Generated by Django 4.2.3 on 2025-01-22 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0009_remove_registration_traslado_registration_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPasiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Estado de la matrícula',
                'verbose_name_plural': 'Estados de la matrícula',
            },
        ),
        migrations.CreateModel(
            name='RegistrationPasiveStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pasive_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registrationpasivestate')),
            ],
            options={
                'verbose_name': 'Log de Estado Pasivo',
                'verbose_name_plural': 'Logs de Estado Pasivo',
            },
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
        migrations.AddField(
            model_name='registration',
            name='has_theorical_exam_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_management.trasnferofregistration'),
        ),
        migrations.DeleteModel(
            name='RegistrationContract',
        ),
        migrations.DeleteModel(
            name='RegistrationState',
        ),
        migrations.AddField(
            model_name='registrationpasivestatelog',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registration'),
        ),
        migrations.AddField(
            model_name='registration',
            name='pasive_states',
            field=models.ManyToManyField(related_name='registrations', through='administrative_management.RegistrationPasiveStateLog', to='administrative_management.registrationpasivestate'),
        ),
    ]
