# Generated by Django 4.2.3 on 2025-01-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0010_registrationpasivestate_registrationpasivestatelog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticalExam',
        ),
        migrations.DeleteModel(
            name='TheoricalExam',
        ),
        migrations.AlterField(
            model_name='registrationpasivestatelog',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
