# Generated by Django 4.2.3 on 2025-01-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0012_registration_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('set_pasive_true', models.BooleanField(default=False)),
                ('set_theorical_true', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado de la matrícula',
                'verbose_name_plural': 'Estados de la matrícula',
            },
        ),
        migrations.CreateModel(
            name='RegistrationStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registration')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registrationstate')),
            ],
            options={
                'verbose_name': 'Log de Estado Pasivo',
                'verbose_name_plural': 'Logs de Estado Pasivo',
            },
        ),
        migrations.RemoveField(
            model_name='registrationpasivestatelog',
            name='pasive_state',
        ),
        migrations.RemoveField(
            model_name='registrationpasivestatelog',
            name='registration',
        ),
        migrations.DeleteModel(
            name='RegistrationPasiveState',
        ),
        migrations.DeleteModel(
            name='RegistrationPasiveStateLog',
        ),
        migrations.AlterField(
            model_name='registration',
            name='pasive_states',
            field=models.ManyToManyField(related_name='registrations', through='administrative_management.RegistrationStateLog', to='administrative_management.registrationstate'),
        ),
    ]
