# Generated by Django 4.2.3 on 2025-01-22 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0013_registrationstate_registrationstatelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryAppRenovations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='registrationstatelog',
            options={'verbose_name': 'Log de Estado', 'verbose_name_plural': 'Logs de Estado'},
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='pasive_states',
            new_name='states_log',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='transfer',
        ),
        migrations.AddField(
            model_name='registration',
            name='access_to_tests_expire_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrasnferOfRegistration',
        ),
        migrations.AddField(
            model_name='theoryapprenovations',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registration'),
        ),
    ]
