# Generated by Django 4.2.3 on 2025-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0014_theoryapprenovations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='access_to_tests_expire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
