# Generated by Django 4.2.3 on 2025-01-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_tax_remove_product_taxe_rate_product_tax'),
        ('human_resources', '0024_absence_is_justified_absence_is_sick_leave_and_more'),
        ('administrative_management', '0016_remove_registration_data_protection_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_task_completed', models.BooleanField(default=False, verbose_name='administrative_management.FollowingTask')),
            ],
        ),
        migrations.CreateModel(
            name='FollowingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.section'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FollowingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField()),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.following')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.followingform')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registration')),
            ],
        ),
        migrations.CreateModel(
            name='FollowingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loop', models.BooleanField(default=True)),
                ('days_since_register', models.IntegerField(default=0)),
                ('repeat_every_days', models.IntegerField(default=0)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.followingplan')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.followingform')),
            ],
        ),
        migrations.CreateModel(
            name='FollowingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.administrative')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registration')),
            ],
        ),
    ]
