# Generated by Django 4.2.3 on 2025-01-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0017_following_followingform_followingplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrative_management.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='following',
            name='last_task_completed',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='last_task_completed', to='administrative_management.followingtask'),
        ),
    ]
