# Generated by Django 4.2.3 on 2025-01-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0018_following_register_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='last_task_completed',
        ),
        migrations.AddField(
            model_name='following',
            name='following_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrative_management.followingplan'),
            preserve_default=False,
        ),
    ]
