# Generated by Django 4.2.3 on 2025-01-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0019_remove_following_last_task_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingtask',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='followingtask',
            name='register',
        ),
    ]
