# Generated by Django 4.2.3 on 2025-01-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0008_tax_remove_product_taxe_rate_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
                ('insurance_payment_date', models.DateField()),
                ('vehicle_circulation_permission_document', models.FileField(upload_to='docs/vehicles/', verbose_name='Permiso de circulacion')),
                ('technical_data_sheet_document', models.FileField(upload_to='docs/vehicles/', verbose_name='Ficha tecnica')),
                ('insurance_document', models.FileField(upload_to='docs/vehicles/')),
                ('itv_document', models.FileField(upload_to='docs/vehicles/')),
                ('is_active', models.BooleanField(default=True)),
                ('driving_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.drivinglicense')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_fleet.fueltype')),
            ],
        ),
    ]
