# Generated by Django 4.2.3 on 2025-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='docs/vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='itv_document',
            field=models.FileField(blank=True, null=True, upload_to='docs/vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='technical_data_sheet_document',
            field=models.FileField(blank=True, null=True, upload_to='docs/vehicles/', verbose_name='Ficha tecnica'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_circulation_permission_document',
            field=models.FileField(blank=True, null=True, upload_to='docs/vehicles/', verbose_name='Permiso de circulacion'),
        ),
    ]
