# Generated by Django 4.2.3 on 2025-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_fleet', '0002_alter_vehicle_insurance_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
