# Generated by Django 4.2.3 on 2025-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_fleet', '0003_alter_vehicle_insurance_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.FileField(default='', upload_to='vehicles/'),
            preserve_default=False,
        ),
    ]
