# Generated by Django 4.2.3 on 2023-07-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschools', '0002_drivingpermission'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drivingschools.drivingpermission')),
                ('school_section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drivingschools.drivingschoolsection')),
                ('test_center', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.testcenter')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.testtype')),
            ],
        ),
    ]
