# Generated by Django 4.2.3 on 2023-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_month_test_num_aptos_test_num_aptos_1_conv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
